services:
  # database
  mysql:
    image: mysql:8.0.39-debian
    container_name: mysql-laravel_project_starter
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      # MYSQL_USER: root
    ports:
      - "3311:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-laravel_project_starter
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/
      PHP_MEMORY_LIMIT: 1024M
    volumes:
      - ./:/var/www/html
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - mysql

  # nginx
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx-laravel_project_starter
    ports:
      - "8090:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # node
  node:
    image: node:22-alpine
    container_name: node-laravel-net_ninja
    working_dir: /var/www/html
    ports:
      - "5173:5173"  # Expose Vite dev server port
    volumes:
      - ./:/var/www/html
    environment:
      - HOST=0.0.0.0  # Allow external connections
    command: sh -c "npm install && npm run dev"
    depends_on:
      - php

volumes:
  mysql-data: